FROM golang:1.23.3-alpine

RUN apk add --no-cache git make bash gcc musl-dev

RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY go.* ./

RUN go mod download

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
